---
name: Check kubernetes

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - .github/workflows/check-kubernetes.yml
  pull_request:
    paths:
      - .github/workflows/check-kubernetes.yml

jobs:
  check-kubernetes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
